function [ res] = gen_parameters( max_value_train, min_value_train, ...
    max_value_test, min_value_test, num_para_train, num_para_test )
%GEN_TRAIN_PARAMETERS Summary of this function goes here
%   Detailed explanation goes here

res.train_para = (max_value_train - min_value_train) * rand(num_para_train,1)...
    + min_value_train;
%training parameters generated by uniform distribution

res.test_para = (max_value_test - min_value_test) * rand(num_para_test,1)...
    + min_value_test;
%test parameters generated by uniform distribution

disp(['minimum value of training parameters ',num2str(min(res.train_para))])
disp(['maximum value of training parameters ',num2str(max(res.train_para))])
disp(['minimum value of test parameters ',num2str(min(res.test_para))])
disp(['maximum value of test parameters ',num2str(max(res.test_para))])

end

